### ISSUE TITLE
Update `.eslintrs.js` to match Airbnb's one

### ISSUE THREAD

**Issue by renatomcamilio** [CodeDoesGood/org-website#22]
This task is going to also add value to the first checklist item of this task: https://github.com/CodeDoesGood/business/issues/41

https://github.com/airbnb/javascript

**Comment by tehstun** [comment]
Update: 

Pull request in place for updating eslint file to extend airbnb coding style. https://github.com/CodeDoesGood/org-website/pull/23

**Comment by renatomcamilio** [comment]
Merged on #23 👍
