### ISSUE TITLE
Need to validate the content of each page with the team

### ISSUE THREAD

**Issue by renatomcamilio** [CodeDoesGood/org-website#6]
- [ ] **Home** (Currently pointing to **About**)
- [ ] **Portfolio**
- [ ] **About** { About Us, Team, Contact Us* (section currently hidden) }
- [ ] **Code of Conduct**
- [ ] **Mission**

**Comment by renatomcamilio** [comment]
Suggestion: since we kinda have too much pages on the website now, maybe we should combine About, Team, and Contact Us.

**Comment by abbeyjackson** [comment]
@renatomcamilio Hey Renato can I get a quick update on the website status?

**Comment by renatomcamilio** [comment]
@abbeyjackson Yep! The updated website has been available at http://codedoesgood.ca -- I also shared with you on Slack and asked you guys to share your thoughts. The content distribution is going to get improved over time when we get some insights from our design volunteers as for theme (currently using a template, I'm sure we can get some volunteers to use the website as a OTL)

**Comment by abbeyjackson** [comment]
@renatomcamilio Is the website complete for now then?

**Comment by abbeyjackson** [comment]
@renatomcamilio Can you change the "join us" link in the team section to: https://github.com/CodeDoesGood/org/wiki/2.-Volunteering

Also can you please add the Low Cost software page:
https://github.com/CodeDoesGood/org/wiki/1.-Low-Cost-Software-for-Non-Profits

And can you explain how the auto import of content works? Is it instantaneous or once a day or...? Just so I know how long to expect changes to the wiki to propagate.

**Comment by renatomcamilio** [comment]
@abbeyjackson never got back to you on this one; So, auto import not implemented yet -- will discuss that with the team I'll put together to take this as OTL 👍 

I can make the changes on the website for now while we don't have the auto import mechanism.

**Comment by renatomcamilio** [comment]
This task doesn't make sense anymore. We are not going to iterate over the version currently live at http://codedoesgood.org; Instead, we are going to have better aligned tasks on the [v2 milestone](https://github.com/CodeDoesGood/org-website/milestone/1)
